config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/ask', to: 'questions#ask'
  get '/answer', to: 'questions#answer'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:question]
    if @question && @question.chars.include?('?')
      @answer = 'Silly question, get dressed and go to work!'
    elsif @question == 'I am going to work'
      @answer = 'Great!'
    else
      @answer = 'I don\'t care, get dressed and go to work!'
    end
    puts @answer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <h1>Stupid coaching</h1>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<% if @question %>
  <p class="message">Your question: <%= @question %> <p>
  <p class="message">Coach answer: <%= @answer %></p>
<% end %>

<%= link_to 'Ask a new question', ask_path, class: 'btn' %>

app/views/questions/ask.html.erb
<p>Ask your coach anything</p>
<%= form_with url: answer_path, local: true, method: 'GET' do |form| %>
  <%= form.label :question%>
  <%= form.text_field :question%>
  <%= form.submit 'Ask' %>
<% end %>